name: Expo CI/CD

on:
  push:
    branches: ['main'] 

jobs:
  build-and-submit:
    name: Build and Submit Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Log in to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Restore service account key
        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > google-play-service-account.json

      - name: Build Android app
        run: eas build --platform android --profile production --non-interactive

      - name: Submit to Google Play
        run: eas submit --platform android --profile production --non-interactive
