name: Expo CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Create Google Play Service Account Key
        run: echo '${{ secrets.GOOGLE_PLAY_KEY }}' > google-play-service-account.json

      # - name: Build Android App
      #   run: eas build --platform android --profile production --non-interactive --output=build.aab

      - name: Submit to Google Play
        run: eas submit --platform android --profile production --non-interactive --path build.aab