name: Expo CI/CD

on:
  push:
    branches:
      - production

jobs:
  build_and_submit:
    name: Build and Submit Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create .env.production.local
        run: |
          echo "EXPO_PUBLIC_SERVER_ADDRESS=${{ secrets.EXPO_PUBLIC_SERVER_ADDRESS }}" >> .env.production.local
          echo "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}" >> .env.production.local
          echo "EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID }}" >> .env.production.local
          echo "EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID }}" >> .env.production.local
          echo "EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID }}" >> .env.production.local

      - name: Create Google Play Service Account Key
        env:
          GOOGLE_PLAY_KEY: ${{ secrets.GOOGLE_PLAY_KEY }}
        run: echo "$GOOGLE_PLAY_KEY" > google-play-service-account.json

      - name: Build and Submit to Google Play
        run: eas build --platform android --profile production --non-interactive --auto-submit